version: '2'
minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9009:9009'
    volumes:
      - './minio/data/:/data'
      - './minio/config:/root/.minio'
    env_file: 
      - common.env
    command: server /data --console-address ":9009"